name: CI-Create-Dashboard

on:
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      environment:
        description: "Select the deployment environment"
        required: true
        type: choice
        options:
          - QA
          - UAT
          - PROD

env:
  REGISTRY: <name of registry>

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint Code Base

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_and_push:
    runs-on: ubuntu-latest
    name: Build and Push Docker Image
    needs: lint

    outputs:
      commit_hash: ${{ steps.commit_hash.outputs.commit_hash }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Install Ant
        run: sudo apt install -y ant

      - name: Build with Ant
        run: ant createScenariosDashboard -buildfile build.xml -Denvironment=${{ github.event.inputs.environment }}

      - id: commit_hash
        run: echo "commit_hash=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    environment:
      name: ${{ github.event.inputs.environment }}

    steps:
      - name: Display Environment
        run: |
          echo "Deploying to ${{ github.event.inputs.environment }}"

      - name: Deploy
        run: |
          if [ "${{ github.event.inputs.environment }}" = "QA" ]; then
            echo "Deploying to QA..."
          elif [ "${{ github.event.inputs.environment }}" = "UAT" ]; then
            echo "Deploying to UAT..."
          else
            echo "Deploying to PROD..."
          fi
